from openpyxl import Workbook
from openpyxl import load_workbook
from django.utils import timezone
from tablib import Dataset
# from ATS_app.models import ATTENDANCE_INFO

wb = Workbook()

ws = wb.active


ws.append(["ATTENDANCE_ID", "DATE" ,"HOUR", "SUBJECT_ID", "STATUS"])

attendance = [
    (20001, "Emma", "Johnson",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20002, "Liam", "Smith",'2024-04-03','PRESENT','PRESENT','PRESENT','ABSENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20003, "Olivia", "Williams",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20004, "Noah", "Brown",'2024-04-03','PRESENT','PRESENT','PRESENT','ABSENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20005, "Ava", "Jones",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20006, "William", "Davis",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20007, "Sophia", "Miller",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20008, "James", "Wilson",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','ABSENT','PRESENT','PRESENT','PRESENT'),
    (20009, "Isabella", "Taylor",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20010, "Benjamin", "Anderson",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','ABSENT','PRESENT','PRESENT','PRESENT'),
    (20011, "Mia", "Martinez",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20012, "Ethan", "Thomas",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20013, "Charlotte", "Garcia",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20014, "Amelia", "Hernandez",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','ABSENT','PRESENT','PRESENT'),
    (20015, "Henry", "Robinson",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20016, "Ella", "Young",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','ABSENT','PRESENT','PRESENT'),
    (20017, "Jacob", "Rodriguez",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20018, "Avery", "Lewis",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','ABSENT','PRESENT','PRESENT'),
    (20019, "Sofia", "Hall",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20020, "Michael", "Allen",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','ABSENT','PRESENT','PRESENT'),
    (20021, "Scarlett", "Scott",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT'),
    (20022, "Logan", "King",'2024-04-03','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT','PRESENT')]

for row in attendance:
    ws.append(row)
wb.save('attendance.xlsx')